/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable react/prop-types */
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="h-20">
          <Navbar/>
        



        


      <aside className=''>
      {children}
      </aside>
      </div>
      </body>
      </html>
    
    
  );
}
