/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable react/prop-types */

import "./globals.css";
import Navbar from "../components/navbar"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
{/* <Provider> */}
<body className=" overflow-x-hidden">
        <div className="  ">
          <Navbar/>
      <aside className=''>
      {children}
      </aside>
      </div>
      </body>
      {/* </Provider> */}
      
      </html>
    
    
  );
}
